name: "Validate Gradle Wrapper"
on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
